import frame as frame
import resource as resource
from frame._app import app
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN"
          "DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title> epydoc1 </title>
</head>
<frameset cols="20%,80%">
  <frameset rows="30%,70%">
    <frame resource>="toc.html" name="moduleListFrame"
           id="moduleListFrame" />
           <span class="options">[<a href="javascript:void(0);" class="privatelink"
            onclick="toggle_private();">hide&nbsp;private</a>]</span>
            <span class="epydoc">[<a href="javascript:void(0);" class="epydoc.js"
              onclick="toggle_private();">hide&nbsp;private</a>]</span>
            <span class="epydoc">[<a href="javascript:void(0);" class="epydoc.css"
              onclick="toggle_private();">hide&nbsp;private</a>]</span>

            <script type="text/javascript"></script>

    <frame.routes.connect.html(app)>="toc-everything.html" name="moduleFrame"
           id="moduleFrame" />
    def routes():
	    Epydoc
  </frameset>
  <span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <span class="epydoc">[<a href="inh_example.Bird-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Bird">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Bird
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Bird-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Bird</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Bird">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Bird</strong>
</pre>

<hr />


    <span class="epydoc">[<a href="inh_example.Bird-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Bird">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Bird
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Bird-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Bird</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Bird">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Bird</strong>
</pre>

<hr />


    <span class="epydoc">[<a href="inh_example.Bug-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
       <!-- Project homepage -->
       <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Bug">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Bug
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Bug-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Bug</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Bug">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Bug</strong>
</pre>

<hr />

    
    <span class="epydoc">[<a href="inh_example.Bug-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Bug">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Bug
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Bug-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Bug</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Bug">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Bug</strong>
</pre>

<hr />


    <span class="epydoc">[<a href="inh_example.Fish-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
       <!-- Project homepage -->
       <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
       <!-- Project homepage -->
       <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Fish">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Fish
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Fish-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Fish</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Fish">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Fish</strong>
</pre>

<hr />


    <span class="epydoc">[<a href="inh_example.Fish-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Fish">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Fish
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Fish-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Fish</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Fish">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Fish</strong>
</pre>

<hr />


    <span class="epydoc">[<a href="inh_example.Human-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Human">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Human
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Human-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Human</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Human">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+        
         |        
    <a href="inh_example.Mammal-class.html">Mammal</a> --+    
             |    
       <a href="inh_example.Primate-class.html">Primate</a> --+
                 |
                <strong class="uidshort">Human</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Programmer-class.html">Programmer</a></li>  </ul>
</dd></dl>

<hr />

a name="section-MethodDetails"></a>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr bgcolor="#70b0f0" class="table-header">
  <td colspan="2" class="table-header">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr valign="top">
        <td align="left"><span class="table-header">Method Details</span></td>
        <td align="right" valign="top"
         ><span class="options">[<a href="#section-MethodDetails"
         class="privatelink" onclick="toggle_private();"
         >hide private</a>]</span></td>
      </tr>
    </table>
  </td>
</tr>
</table>
<a name="talk"></a>
<div>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr><td>
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr valign="top"><td>
  <h3 class="epydoc"><span class="sig"><span class="sig-name">talk</span>(<span class="sig-arg">self</span>,
        <span class="sig-arg">animal</span>)</span>
  </h3>
  </td><td align="right" valign="top"
    ><span class="codelink"><a href="inh_example-pysrc.html#Human.talk">source&nbsp;code</a></span>&nbsp;
    </td>
  </tr></table>
  
  <p>Talk to the given animal.  Depending on what kind of creature 
  <code>animal</code> is, it may or may not be responsive.</p>
  <dl class="fields">
  </dl>
</td></tr></table>
</div>
<br />


    <span class="epydoc">[<a href="inh_example.Human-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Human">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Human
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Human-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Human</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Human">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+        
         |        
    <a href="inh_example.Mammal-class.html">Mammal</a> --+    
             |    
       <a href="inh_example.Primate-class.html">Primate</a> --+
                 |
                <strong class="uidshort">Human</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Programmer-class.html">Programmer</a></li>  </ul>
</dd></dl>

<hr />

<a name="section-MethodDetails"></a>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr bgcolor="#70b0f0" class="table-header">
  <td colspan="2" class="table-header">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr valign="top">
        <td align="left"><span class="table-header">Method Details</span></td>
        <td align="right" valign="top"
         ><span class="options">[<a href="#section-MethodDetails"
         class="privatelink" onclick="toggle_private();"
         >hide private</a>]</span></td>
      </tr>
    </table>
  </td>
</tr>
</table>
<a name="talk"></a>
<div>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr><td>
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr valign="top"><td>
  <h3 class="epydoc"><span class="sig"><span class="sig-name">talk</span>(<span class="sig-arg">self</span>,
        <span class="sig-arg">animal</span>)</span>
  </h3>
  </td><td align="right" valign="top"
    ><span class="codelink"><a href="inh_example-pysrc.html#Human.talk">source&nbsp;code</a></span>&nbsp;
    </td>
  </tr></table>
  
  <p>Talk to the given animal.  Depending on what kind of creature 
  <code>animal</code> is, it may or may not be responsive.</p>
  <dl class="fields">
  </dl>
</td></tr></table>
</div>
<br />


    <span class="epydoc">[<a href="inh_example.Mammal-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Mammal">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Mammal
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Mammal-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Mammal</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Mammal">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Mammal</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Primate-class.html">Primate</a></li>  </ul>
</dd></dl>

<hr />


    <span class="epydoc">[<a href="inh_example.Mammal-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
         <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Mammal">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Mammal
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Mammal-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Mammal</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Mammal">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+
         |
        <strong class="uidshort">Mammal</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Primate-class.html">Primate</a></li>  </ul>
</dd></dl>

<hr />


    <span class="epydoc">[<a href="inh_example.Primate-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Primate">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Primate
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Primate-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Primate</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Primate">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+    
         |    
    <a href="inh_example.Mammal-class.html">Mammal</a> --+
             |
            <strong class="uidshort">Primate</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Human-class.html">Human</a></li>  </ul>
</dd></dl>

<hr />


    <span class="epydoc">[<a href="inh_example.Primate-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Primate">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Primate
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Primate-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Primate</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Primate">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+    
         |    
    <a href="inh_example.Mammal-class.html">Mammal</a> --+
             |
            <strong class="uidshort">Primate</strong>
</pre>

<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Human-class.html">Human</a></li>  </ul>
</dd></dl>

<hr />


    <span class="epydoc">[<a href="inh_example.Programmer-class.html" class="epydoc.js"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Programmer">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Programmer
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Programmer-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Programmer</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Programmer">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+            
         |            
    <a href="inh_example.Mammal-class.html">Mammal</a> --+        
             |        
       <a href="inh_example.Primate-class.html">Primate</a> --+    
                 |    
             <a href="inh_example.Human-class.html">Human</a> --+
                     |
                    <strong class="uidshort">Programmer</strong>
</pre>

<hr />

<a name="section-MethodDetails"></a>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr bgcolor="#70b0f0" class="table-header">
  <td colspan="2" class="table-header">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr valign="top">
        <td align="left"><span class="table-header">Method Details</span></td>
        <td align="right" valign="top"
         ><span class="options">[<a href="#section-MethodDetails"
         class="privatelink" onclick="toggle_private();"
         >hide private</a>]</span></td>
      </tr>
    </table>
  </td>
</tr>
</table>
<a name="squish"></a>
<div>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr><td>
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr valign="top"><td>
  <h3 class="epydoc"><span class="sig"><span class="sig-name">squish</span>(<span class="sig-arg">self</span>,
        <span class="sig-arg">bug</span>,
        <span class="sig-arg">code</span>)</span>
  </h3>
  </td><td align="right" valign="top"
    ><span class="codelink"><a href="inh_example-pysrc.html#Programmer.squish">source&nbsp;code</a></span>&nbsp;
    </td>
  </tr></table>
  
  <p>Remove the given bug from the given program.</p>
  <dl class="fields">
    <dt>Parameters:</dt>
    <dd><ul class="nomargin-top">
        <li><strong class="pname"><code>bug</code></strong> (<a href="inh_example.Bug-class.html" class="link">Bug</a>) - The bug that should be removed from <code>code</code>.</li>
    </ul></dd>
  </dl>
</td></tr></table>
</div>
<br />


    <span class="epydoc">[<a href="inh_example.Programmer-class.html" class="epydoc.css"
    onclick="toggle_private();">hide&nbsp;private</a>]</span>
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Programmer">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Programmer
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Programmer-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Programmer</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Programmer">source&nbsp;code</a></span></p>
<pre class="base-tree">
<a href="inh_example.Animal-class.html">Animal</a> --+            
         |            
    <a href="inh_example.Mammal-class.html">Mammal</a> --+        
             |        
       <a href="inh_example.Primate-class.html">Primate</a> --+    
                 |    
             <a href="inh_example.Human-class.html">Human</a> --+
                     |
                    <strong class="uidshort">Programmer</strong>
</pre>

<hr />

<a name="section-MethodDetails"></a>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr bgcolor="#70b0f0" class="table-header">
  <td colspan="2" class="table-header">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr valign="top">
        <td align="left"><span class="table-header">Method Details</span></td>
        <td align="right" valign="top"
         ><span class="options">[<a href="#section-MethodDetails"
         class="privatelink" onclick="toggle_private();"
         >hide private</a>]</span></td>
      </tr>
    </table>
  </td>
</tr>
</table>
<a name="squish"></a>
<div>
<table class="details" border="1" cellpadding="3"
       cellspacing="0" width="100%" bgcolor="white">
<tr><td>
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr valign="top"><td>
  <h3 class="epydoc"><span class="sig"><span class="sig-name">squish</span>(<span class="sig-arg">self</span>,
        <span class="sig-arg">bug</span>,
        <span class="sig-arg">code</span>)</span>
  </h3>
  </td><td align="right" valign="top"
    ><span class="codelink"><a href="inh_example-pysrc.html#Programmer.squish">source&nbsp;code</a></span>&nbsp;
    </td>
  </tr></table>
  
  <p>Remove the given bug from the given program.</p>
  <dl class="fields">
    <dt>Parameters:</dt>
    <dd><ul class="nomargin-top">
        <li><strong class="pname"><code>bug</code></strong> (<a href="inh_example.Bug-class.html" class="link">Bug</a>) - The bug that should be removed from <code>code</code>.</li>
    </ul></dd>
  </dl>
</td></tr></table>
</div>
<br />


    <script type="text/javascript"></script>


  <frame src="inh_example-module.html" name="mainFrame" id="mainFrame" />
</frameset>
<span class="options">[<a href="javascript:void(0);" class="privatelink"
  onclick="toggle_private();">hide&nbsp;private</a>]</span>
  <span class="epydoc">[<a href="inh_example.Animal-class.html" class="epydoc.js"
  onclick="toggle_private();">hide&nbsp;private</a>]</span>
  <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Animal">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Animal
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Animal-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Animal</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Animal">source&nbsp;code</a></span></p>
<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Bird-class.html">Bird</a></li><li>, <a href="inh_example.Bug-class.html">Bug</a></li><li>, <a href="inh_example.Fish-class.html">Fish</a></li><li>, <a href="inh_example.Mammal-class.html">Mammal</a></li>  </ul>
</dd></dl>

<hr />


  <span class="epydoc">[<a href="inh_example.Animal-class.html" class="epydoc.css"
  onclick="toggle_private();">hide&nbsp;private</a>]</span>
  <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
    <table class="navbar" border="0" width="100%" cellpadding="0"
       bgcolor="#a0c0ff" cellspacing="0">
  <tr valign="middle">
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="http://epydoc.sourceforge.net">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%%">
  <tr>
    <td align="left" class="footer">
    Generated by Epydoc 3.0.1 on Wed Jan 30 14:10:16 2008
    </td>
    <td align="right" class="footer">
      <a target="mainFrame" href="http://epydoc.sourceforge.net"
        >http://epydoc.sourceforge.net</a>
    </td>
  </tr>
</table>
  <!-- Home link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Home&nbsp;&nbsp;&nbsp;</th>
          <!-- Tree link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Trees&nbsp;&nbsp;&nbsp;</th>
      <!-- Index link -->
      <th bgcolor="#70b0f0" class="navbar-select"
          >&nbsp;&nbsp;&nbsp;Indices&nbsp;&nbsp;&nbsp;</th>
          <!-- Help link -->
      <th bgcolor="#70b0f0" class="navbar-select"
      >&nbsp;&nbsp;&nbsp;Help&nbsp;&nbsp;&nbsp;</th>
      <!-- Project homepage -->
      <th class="navbar" align="right" width="100%">
        <table border="0" cellpadding="0" cellspacing="0">
          <tr><th class="navbar" align="center"
            ><a class="navbar" target="_top" href="inh_example-pysrc.html#Animal">epydoc examples</a></th>
          </tr></table></th>
  </tr>
</table>
<table width="100%" cellpadding="0" cellspacing="0">
  <tr valign="top">
    <td width="100%">
      <span class="breadcrumbs">
        <a href="inh_example-module.html">Module&nbsp;inh_example</a> ::
        Class&nbsp;Animal
      </span>
    </td>
    <td>
      <table cellpadding="0" cellspacing="0">
        <!-- hide/show private -->
        <tr><td align="right"><span class="options">[<a href="javascript:void(0);" class="privatelink"
    onclick="toggle_private();">hide&nbsp;private</a>]</span></td></tr>
        <tr><td align="right"><span class="options"
            >[<a href="frames.html" target="_top">frames</a
            >]&nbsp;|&nbsp;<a href="inh_example.Animal-class.html"
            target="_top">no&nbsp;frames</a>]</span></td></tr>
      </table>
    </td>
  </tr>
</table>
<h1 class="epydoc">Class Animal</h1><p class="nomargin-top"><span class="codelink"><a href="inh_example-pysrc.html#Animal">source&nbsp;code</a></span></p>
<dl><dt>Known Subclasses:</dt>
<dd>
      <ul class="subclass-list">
<li><a href="inh_example.Bird-class.html">Bird</a></li><li>, <a href="inh_example.Bug-class.html">Bug</a></li><li>, <a href="inh_example.Fish-class.html">Fish</a></li><li>, <a href="inh_example.Mammal-class.html">Mammal</a></li>  </ul>
</dd></dl>

<hr />

  <script type="text/javascript"></script>

  
  <a name="section-InstanceMethods"></a>
  <table class="summary" border="1" cellpadding="3"
         cellspacing="0" width="100%" bgcolor="white">
  <tr bgcolor="#70b0f0" class="table-header">
    <td colspan="2" class="table-header">
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr valign="top">
          <td align="left"><span class="table-header">Instance Methods</span></td>
          <td align="right" valign="top"
           ><span class="options">[<a href="#section-InstanceMethods"
           class="privatelink" onclick="toggle_private();"
           >hide private</a>]</span></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
      <td width="15%" align="right" valign="top" class="summary">
        <span class="summary-type">&nbsp;</span>
      </td><td class="summary">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td><span class="summary-sig"><a name="eat"></a><span class="summary-sig-name">eat</span>(<span class="summary-sig-arg">self</span>,
          <span class="summary-sig-arg">food</span>)</span><br />
        Consume the given food object.</td>
            <td align="right" valign="top">
              <span class="codelink"><a href="inh_example-pysrc.html#Animal.eat">source&nbsp;code</a></span>
              
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
  <tr>
      <td width="15%" align="right" valign="top" class="summary">
        <span class="summary-type">&nbsp;</span>
      </td><td class="summary">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td><span class="summary-sig"><a name="sleep"></a><span class="summary-sig-name">sleep</span>(<span class="summary-sig-arg">self</span>,
          <span class="summary-sig-arg">time</span>)</span><br />
        Sleep for the given period of time.</td>
            <td align="right" valign="top">
              <span class="codelink"><a href="inh_example-pysrc.html#Animal.sleep">source&nbsp;code</a></span>
              
            </td>
          </tr>
        </table>
        
      </td>
    </tr>
  </table>

</html>
